vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - gabrielbb.vscode-lombok
tasks:
  - name: docker daemon
    before: sudo docker-up
